### PR TITLE
feat(md): Support customising property table columns

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
Not sure if this is the best implementation, but it would be great to be able to remove the "Deprecated"column from output, until we have a deprecated property.

**Comment by dblanchette** [comment]
If I understand correctly, the idea is to allow not including all of the columns as well as changing the order, correct?

If so, I think the wording for the configuration option could be improved. Also, it should be clear this only applies to Markdown templates.

Otherwise, I think it's great, thanks!

**Comment by alexjurkiewicz** [comment]
Sorry for the slow reply. I appreciate the feedback but won't have time to
follow up for at least a few weeks. It will remain in my backlog 👍

**Review by sennhann29 — APPROVED** [review]

**Comment by dblanchette** [comment]
Merged via #224

**Comment by alexjurkiewicz** [comment]
Thank you for your time Denis!

**Pull request closed without merging**
