### PR TITLE
Add examples_as_yaml option

### PR DESCRIPTION
**Pull request by hbuckle**
Adds an option to display examples as YAML instead of JSON.
I'm not too familiar with Python, let me know if I've missed anything.

### CODE REVIEW

**Comment by dblanchette** [comment]
Hi @hbuckle , thanks for your contribution!

I have some edits I would like to make (fix some tests and regenerate the cases as well as updating the MD template to remove whitespaces).

I already made the changes locally, but am not allowed to push to your branch `examples_as_yaml` in your fork. You can follow the doc here to allow that: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Otherwise, I would need to create a new PR and I don't want to steal your thunder ;)

**Comment by hbuckle** [comment]
@dblanchette - apparently that option isn't available for PRs from organization accounts, but I added you to the  clearbank /
json-schema-for-humans repo directly, hopefully that will work

**Comment by dblanchette** [comment]
It's weird because it's telling me I have access, but I could not push. I created #96 to circumvent that problem, sorry!

**Comment by dblanchette** [comment]
Released in version 0.34.0

**Pull request closed without merging**
