### PR TITLE
Fix markdown "break on newline" configurability

### PR DESCRIPTION
**Pull request by threema-danilo**
Previously, `"break-on-newline": True` was part of the default markdown options. The user could override the configuration value, thus turning it into `"break-on-newline": False`, but unfortunately the markdown2 library ignores the value of the option, and always sets it to `True` if the key is passed in.

The `break-on-newline` extra is deprecated, there is a new option since 2.4.11: `breaks` https://github.com/trentm/python-markdown2/wiki/breaks Unfortunately, markdown2 overrides the `breaks.on_newline` configuration if `break-on-newline` is present in the extras, meaning that this doesn't work for disabling "break on newline" either.

This means that right now there is _no_ way for the users of jsfh to disable line breaks on newlines. To fix this, remove `break-on-newline` from the default markdown options. If (and only if) the `breaks` config is _not_ set by the user, a `breaks` config is added to the defaults that inserts line breaks on newlines by default.

### CODE REVIEW

**Comment by threema-danilo** [comment]
(As a sidenote, the `markdown2` library seems quite convoluted to me, with regards to the parsing of options... Have you considered moving to a standards-conforming library like [commonmark](https://pypi.org/project/commonmark/)?

**Comment by estan** [comment]
I'd love to see this get it so that we can disable break on newline. Is there more work to be done here @dblanchette ?

**Comment by estan** [comment]
@threema-danilo I think it would also be good to update the `default` in `config_schema.json`, perhaps with a comment about the conditional-ness.

**Comment by threema-danilo** [comment]
@estan thanks for the update! I don't currently have the free capacity to work on this issue, but feel free to push changes to my branch in order for it to conform to your project standards 🙂

**Pull request merged**
