### PR TITLE
Add support for JSON-Schema "examples"-property, UTF-8 compatibility in generated result

### PR DESCRIPTION
**Pull request by MihailMiller**
Dear maintainers,

first of all I would like to thank you for this wonderful Python library. For a current research project we need the presentation of JSON-examples in the HTML-documentation of our JSON-schemas. I have made the necessary changes to a local version of this library and would like to share them with you.
The 2 changes made are:
1. representation of the property "examples" (not supported so far):

image

2. decoding unicode-escapes in the generated result

I'm looking forward to your review.

Kind regards

### CODE REVIEW

**Comment by dblanchette** [comment]
Hi @MihailMiller, that is an interesting feature, thank you very much for the contribution.

I did some changes on my side and I would like to know your opinion:

- Removed the prettify JS script on load. We can set an indent on the `tojson` filter to get a similar result. In general, for this lib, I think it is best to do work at generation time so that the rendered page is smooth even for big schemas.
- Removed `get_examples`. I think `property.get("examples") or []` is enough. Unless we want to ignore `null`, but wouldn't that be a valid example?
- Removed the show/hide button for small examples. I re-used the same function than the one used to determine if a description is short. When it is less than ~8 lines of text, there won't be a collapsible section. I could make this configurable if that is annoying.
- Removed JS for show/hide button using only HTML and CSS instead
- Removed `jsonTree.cs` and `jsonTree.js` reference. They are not included in the commit. Leftover?
- Added a unit test

As for the decoding fix, could you provide an example of a schema where you had a problem? Also, which OS and version of Python are you using?
I tried to add the letter `ẞ` like in your example and I don't see a difference between running with or without the added line (`result_file.write(result.replace("\\/", "/").encode().decode("unicode_escape"))`). I am on Windows though, so that might be it. I see that they are not rendered correctly in descriptions and I will open a separate issue for that.

If that is ok with you, I would [push my changes to your branch](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so that I don't have to open another Pull Request.

Here is an example with the latest changes:
chrome_jUV0nUg0XT

<details>
<summary>Source schema:</summary>

```{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "the person's first name",
      "title": "Person",
      "examples": ["Guido", "BDFL"]
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name.",
      "title": "Person",
      "examples": ["Van Rossum"]
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0,
      "title": "Person",
      "examples": [64]
    },
    "moreInfo": {
      "description": "Any more info you want as an object",
      "type": "object",
      "examples": [
        {
          "birthplace": "Haarlem, Netherlands",
          "gender": "male",
          "height_cm": 175,
          "motto": "Beautiful is better than ugly.\\nExplicit is better than implicit.\\nSimple is better than complex.\\nComplex is better than complicated.\\nFlat is better than nested.\\nSparse is better than dense.\\nReadability counts.\\nSpecial cases aren't special enough to break the rules.\\nAlthough practicality beats purity.\\nErrors should never pass silently.\\nUnless explicitly silenced.\\nIn the face of ambiguity, refuse the temptation to guess.\\nThere should be one-- and preferably only one --obvious way to do it.\\nAlthough that way may not be obvious at first unless you're Dutch.\\nNow is better than never.\\nAlthough never is often better than *right* now.\\nIf the implementation is hard to explain, it's a bad idea.\\nIf the implementation is easy to explain, it may be a good idea.\\nNamespaces are one honking great idea -- let's do more of those!"
        }
      ]
    }
  }
}```
</details>

Once again, thanks for the contribution, it is really appreciated.

**Comment by MihailMiller** [comment]
Hi @dblanchette, 
thank you for looking into this and improving my code. The changes you made make perfect sense and I already allowed you to push your changes to my branch by checking the associated checkbox. As for the decoding fix: I also developed on Windows and the Unicode characters were escaped in the HTML, oddly enough I can't reproduce the issue on Chrome anymore by changing the line back to "result_file.write(result)". Possibly the issue was caused due to my Chrome being outdated or it was an issue with the browser cache.
For Now everything is rendering perfectly on Windows 10 Chrome and Firefox:
image
image

Like you mentioned Internet Explorer and Microsoft Edge are not rendering the ß and Umlauts correctly for the Description- and Default-Value (for the examples-Value everything works fine in Internet Explorer):
image

The fix for the Unicode-Escapes I implemented only works in Microsoft Edge now:
**with "result_file.write(result.replace("\\/", "/").encode().decode('unicode_escape'))"**
image

**with "result_file.write(result)"**
81097534-57934100-8f08-11ea-80ee-cdd187bd6aaa

(here it also displays the JSON without indents)

Either way the Umlauts are not displayed correctly in those browsers.

Thank You

Kind regards

**Comment by dblanchette** [comment]
Thanks again @MihailMiller for the detailed reply.

I think I found the solution for the descriptions. There was no charset declared in the output HTML file. Internet Explorer and Edge assumes [cp1252](https://en.wikipedia.org/wiki/Windows-1252) in that case.
Setting it to UTF-8 allows displaying German and French characters and even emojis in Chrome, Firefox, Internet Explorer, and Edge.

For the examples, I think the issue is the `ensure_ascii` parameter for Python's json.dump, see https://docs.python.org/3/library/json.html#json.dump. Setting it to False seems to solve the issue of not being able to display certain letters.

I will merge and release the changes. Let me know if there is a problem with the solution.

**Comment by MihailMiller** [comment]
Thank you for merging and also for fixing the UTF-8 issues! That are interesting points about the charset declaration and the ensure_ascii parameter, thanks for clarifying. Now everything displays just like it is intended to be. 🎉

The only issue I noticed is with the first "show/hide"-button: the target's id is starting with a digit- that's why it is not showing/hiding the examples.
image

When you set the ID in a way, that it starts with a letter, everything works fine. (that's quite strange because HTML5 allows IDs to start with digits) [for example change "{{ index }}_ex{{ loop.index }}" to "id{{ index }}_ex{{ loop.index }}"]

**Comment by dblanchette** [comment]
Interesting, I ensured the ids for other elements could not start with a number, but did not think about the id for examples. I will publish a fix tomorrow (I'm on eastern time).

**Comment by dblanchette** [comment]
I just released version 0.8.1 which should fix the issue with IDs for examples starting with a digit.

Kind regards

**Pull request merged**
